# -*- coding: utf-8 -*-
"""과제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EbxGklbLJXdeempiXUsBpYiYForl45ih
"""

import requests
from bs4 import BeautifulSoup
import pandas
import matplotlib as mpl
import matplotlib.pyplot as plt

!pip install requests
!pip install bs4
!pip install pandas
!pip install matplotlib
!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import time
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument('--headless')      
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver', options=options)

url = "https://www.weather.go.kr/w/obs-climate/land/city-obs.do?auto_man=m&stn=0&dtm=&type=t99&reg=100&tm=" 
driver.get(url)

source = requests.get('https://www.weather.go.kr/w/obs-climate/land/city-obs.do')
soup = BeautifulSoup(source.content,"html.parser")

table = soup.find('table',{'class':'table-col'})
data = []

print("#"*30)
print("\nHello! Here's today's weather!\n")
print("#"*30)

for tr in table.find_all('tr'):
  tds = list(tr.find_all('td'))
  for td in tds:
    if td.find('a'):
      point = td.find('a').text
      temp = tds[5].text
      humidity = tds[9].text
      print("{0:<7} {1:<7} {2:<7}".format(point, temp, humidity))
      data.append([point, temp, humidity])
   

local = []
temp_n = []
temp_1 = []
temp_3 = []
temp_12 = []

user = input()

time.sleep(10)

for i in range(1,96):
  name = driver.find_element_by_xpath(f'//*[@id="weather_table"]/tbody/tr[{i}]/td[1]').text
  local.append(name)

  name1 = driver.find_element_by_xpath(f'//*[@id="weather_table"]/tbody/tr[{i}]/td[6]').text
  temp_n.append(name1)

serch = driver.find_element_by_xpath('//*[@id="default-form"]/div[2]/div/a[3]')
serch.click()

for i in range(1,96):
  name2 = driver.find_element_by_xpath(f'//*[@id="weather_table"]/tbody/tr[{i}]/td[6]').text
  temp_1.append(name2)

serch = driver.find_element_by_xpath('//*[@id="default-form"]/div[2]/div/a[2]')
serch.click()

for i in range(1,96):
  name3 = driver.find_element_by_xpath(f'//*[@id="weather_table"]/tbody/tr[{i}]/td[6]').text
  temp_3.append(name3)

serch = driver.find_element_by_xpath('//*[@id="default-form"]/div[2]/div/a[1]')
serch.click()

for i in range(1,96):
  name4 = driver.find_element_by_xpath(f'//*[@id="weather_table"]/tbody/tr[{i}]/td[6]').text
  temp_12.append(name4)

if user in local:
  p = local.index(user)
  print(f'''        지역 - {user}
        현재 온도 - {temp_n[p]}
        1시간 전의 온도 - {temp_1[p]}
        3시간 전의 온도 - {temp_3[p]}
        12시간 전의 온도 - {temp_12[p]}
        ''')
